# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI Build Flow

on:
  [workflow_dispatch]
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      
      - name: Build service with Maven
        run: |
          cd mms-inventory-service
          mvn clean package -DskipTests

      - name: Install Pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.0.0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: leezonghan19
          password: Siv170013! # Use DOCKER_ACCESS_TOKEN instead if applicable

      - name: Build and Publish Docker Image
        run: |
          cd mms-inventory-service
          pack build leezonghan19/mms-inventory-service:latest \
            --builder paketobuildpacks/builder:base \
            --path target/*.jar \
            --publish

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      # - name: Update dependency graph
      # uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6